name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then echo "ERROR SSH_PRIVATE_KEY is empty"; else echo "OK SSH_PRIVATE_KEY found"; fi
          if [ -z "${{ secrets.VPS_HOST }}" ]; then echo "ERROR VPS_HOST is empty"; else echo "OK VPS_HOST found"; fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            cd /docker/sgs-eproc-bi
            git pull origin main
            docker compose up -d --build
            docker compose restart api-gateway postgrest
