name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then echo "❌ SSH_PRIVATE_KEY está VAZIA"; else echo "✅ SSH_PRIVATE_KEY encontrada"; fi
          if [ -z "${{ secrets.VPS_HOST }}" ]; then echo "❌ VPS_HOST está VAZIO"; else echo "✅ VPS_HOST encontrado"; fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            cd /docker/sgs-eproc-bi
            git pull origin main
            docker compose up -d --build
            docker compose restart api-gateway postgrest
